# Generated by Django 5.2.3 on 2025-08-27 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_applied_form_applied_at_applied_form_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_form',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
