# Generated by Django 5.2.3 on 2025-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_applied_form_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
