# Generated by Django 5.2.3 on 2025-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
